version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout

      - run:
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
          name: Install Requirements
          
      - run:
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xmlytest
          name: Test

      - store_test_results:
        path: test-results

      - store_artifacts:
        path: test-results

workflows:
  main:
    jobs:
      - build-and-test
